- name: Install mysql server and client
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server
    - mysql-client

- name: Disable use of auth_sock for root user
  shell: |
    /usr/bin/mysql --host=localhost --execute "UPDATE mysql.user SET plugin = 'mysql_native_password' WHERE User='root';"
  ignore_errors: yes

- name: Setup root user
  mysql_user: 
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
  ignore_errors: yes
  notify: restart mysql

- name: Remove old .my.cnf
  file:
    path: /root/.my.cnf
    state: absent
