- name: Install mysql server and client
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server
    - mysql-client

- name: Setup root user
  mysql_user: 
    name: "{{ mysql_root_user }}"
    password: "{{ mysql_root_password }}"
  ignore_errors: yes
